### ISSUE TITLE
Error: could not load model.

### ISSUE THREAD

**Issue by tphankr** [lynguyenminh/image-classification-pytorch#5]
Thank you for your nice code.
plz help us, I face the error: Error: Could not load model.
(when I typed python train.py)
![image](https://user-images.githubusercontent.com/37217354/220020121-0c39c015-c238-4a4b-8a9f-aac3640a0c4e.png)

![image](https://user-images.githubusercontent.com/37217354/220020446-7f2346f5-3c10-4ca0-b73a-7801da38f853.png)
Thanks.

**Comment by lynguyenminh** [comment]
Hi, 
You should remove the checkpoint in the config.yaml file.
![image](https://user-images.githubusercontent.com/82688630/220037682-29b4c279-8d48-4111-937f-4fc74d409f79.png)

Hope this helps!

**Comment by tphankr** [comment]
Thank you @lynguyenminh. I followed your hint and did. 
I am wondering that after predict results which save at .csv file. But, I want to save/copy those images to new folder name. Can/how we do that?  (I mean, if the image is duck, it will save o new folder name with the same name in another folder).

Thanks.

**Comment by lynguyenminh** [comment]
> if the image is duck, it will save o new folder name with the same name in another folder).

Hi @tphankr 

You can simply customize the code in src/utils/predict_model.py (line 16) to save the test image or anything else you want instead of saving it to a CSV file.

**Comment by tphankr** [comment]
Thank you @lynguyenminh.
